### ISSUE TITLE
SQLite storage backends

### ISSUE THREAD

**Issue by femtotrader** [ionrock/cachecontrol#46] opened 2014-12-12 17:10 UTC
Hello,

it will be nice if CacheControl could provide SQLite support.

Kind regards

**Comment by ssokolow** [comment] 2015-01-07 10:00
I actually have an old httplib2-based thing I'm migrating to Requests and I had to keep the old SQLite-based cache I jerry-rigged around it because the cache keys are opaque strings. (I needed the ability to access the data externally by columns like URL and INSERT timestamp)

So, while I'd also like support for this, it's not so much the SQLite support that's the problem but the opaque nature of cache keys.

**Comment by ssokolow** [comment] 2015-01-07 10:50
Ok, if I understand your code and naming conventions correctly:

1. You're using the URL as a cache key and storing pickled objects in the cache (rather than using some kind of composite key and storing raw textual HTTP responses like I seem to remember httplib2 doing)
2. You're exposing a public method named `CacheController.cache_url()` which will generate said key.

That means that, if I have the database store the content twice (once as CacheControl expects and once in the raw to protect against class definition changes breaking the ability to unpickle), I should even be able to retrofit the application with a wiki-style `delete()` which just flags things as deleted rather than deleting them.

(And maybe some kind of pre-deployment unit test suite which causes an upgrade attempt to fail catastrophically if there are changes in how `CacheController.cache_url()` works so I can stay on an old version until I've confirmed its safety... probably also good to do that for the schema of whatever's getting pickled so ensure the "and a raw copy" part doesn't break.)

**Comment by ionrock** [comment] 2015-06-29 15:44
I'm going to go ahead and close this one as I don't plan on adding any more backends to CacheControl proper. That said, I'd love to include in the documentation reusable cache backends, so if there is a sqlite backend anyone wants to share, I'm happy to add it to the docs.

**Closed by ionrock** 2015-06-29 15:44 UTC
Labels: enhancement

**Comment by ssokolow** [comment] 2015-06-30 03:28
Fair enough. I've been struggling to get my free time back up from the crash it experienced shortly after I talked to you last, but I'll leave this open as a TODO.

**Comment by ishitatsuyuki** [comment] 2017-10-25 02:03
I have made a brief one at https://github.com/ishitatsuyuki/cachecontrol-sqlite. I will be happy if you could link to that.
